import Color = require('tinycolor2')
import {createStyles} from '@material-ui/core'

export const menuMargin = 10
// export const menuTopPosition = 50
export const menuTopPosition = menuMargin
export const menuItemSpacing = 2
export const panelBorderRadius = 4
export const statusWindowWidth = 400

export const btnColor = Color('#555555')
export const btnTextColor = btnColor.clone().lighten(50)
export const colors = {
  saffron: Color('#f7c431'),
}

// this is the computed height of the Help menu button, which is generated by
// jQuery UI.
export const jQueryAccordionItemHeight = 27

type TriangleOptions = {
  color?: string
  size?: number
}

// eslint-disable-next-line typescript/explicit-function-return-type
export const triangle = ({color, size}: TriangleOptions) =>
  createStyles({
    right: {
      width: 0,
      height: 0,
      border: '0 solid transparent',
      borderBottomWidth: size || 5,
      borderTopWidth: size || 5,
      borderLeft: `6px solid ${color || 'gray'}`,
    },
  })
