/**
 *  Copyright 2017 Mapper Inc.
 *  CONFIDENTIAL. AUTHORIZED USE ONLY. DO NOT REDISTRIBUTE.
 */

export enum AnnotationType {
	UNKNOWN,
	LANE,
	TRAFFIC_DEVICE,
	CONNECTION,
	BOUNDARY,
	TERRITORY,
}
