/**
 *  Copyright 2018 Mapper Inc.
 *  CONFIDENTIAL. AUTHORIZED USE ONLY. DO NOT REDISTRIBUTE.
 */

export enum AnnotationConstructResult {
	SUCCESS,
	DUPLICATE,
	INVALID_INPUT,
	INVALID_STATE,
	CONSTRUCTOR_ERROR,
}
