import {v4 as UUID} from 'uuid'

export const Events = {
  LIGHT_BOX_IMAGE_RAY_UPDATE: UUID(),
  IMAGE_SCREEN_LOAD_UPDATE: UUID(),
  ORIGIN_UPDATE: UUID(),
  TILE_SERVICE_STATUS_UPDATE: UUID(),
  KEYUP: UUID(),
  KEYDOWN: UUID(),
  LIGHTBOX_CLOSE: UUID(),
  IMAGE_EDIT_STATE: UUID(),
  IMAGE_CLICK: UUID(),
  SCENE_UPDATED: UUID(),
}
