/**
 *  Copyright 2018 Mapper Inc.
 *  CONFIDENTIAL. AUTHORIZED USE ONLY. DO NOT REDISTRIBUTE.
 */

import * as UUID from 'uuid'

export const StatusKey = {
	CURRENT_LOCATION_LLA: UUID(),
	CURRENT_LOCATION_UTM: UUID(),
	TILE_SERVER: UUID(),
	CAMERA_TYPE: UUID(),
	TILE_MANAGER_POINT_STATS: UUID(),
	TILE_MANAGER_ANNOTATION_STATS: UUID(),
}
