# application initialization
# Set window dimensions to 0 to maximize.
startup.electron.window.default.width: 0
startup.electron.window.default.height: 0
startup.render.fps: 60
startup.background_color: '#082839'
startup.show_color_picker: true
startup.show_stats_module: true
startup.show_menu: true
startup.show_dev_tools: true
startup.point_cloud_directory:
startup.annotations_path:

# parameters for loading a tile
tile_manager.utm_tile_scale: [10, 10, 10] # conversion from tile index numbers to physical dimensions
tile_manager.super_tile_scale: [100, 100, 50] # ditto; must contain multiples of utm_tile_scale
tile_manager.initial_super_tiles_to_load: 8
tile_manager.maximum_points_to_load: 1000000
tile_manager.sampling_step: 5

# annotator controls
annotator.add_points_to_estimated_ground_plane: true
annotator.generate_voxels_on_point_load: true
annotator.draw_bounding_box: false
annotator.axes_helper_length: 10
annotator.compass_rose_length: 50
annotator.point_render_size: 0.05

# persistence of a data file
output.annotations.json.path: ./data/annotations.json
output.annotations.kml.path: ./data/waypoints.kml
output.annotations.autosave.directory.path: ./data/autosave
output.annotations.autosave.interval.seconds: 300

# Fly-through trajectory file
live_mode.trajectory_path:

# persist trajectories
output.trajectory.csv.path: ./data/trajectory.csv
