# persistence of a data file
output.json.path: ./data/annotations-utm-offset.json
output.kml.path: ./data/path.kml
output.autosave.directory.path: ./data/autosave
output.autosave.interval.seconds: 300

# convert a data file to another format
# You'll need to build the MapAccumulator project to get the jar file onto your system.
# https://github.com/Signafy/Sandbox/tree/master/CloudServices/MapAccumulator#build
conversion.kml.jar: java -classpath /Users/clyde/dev/mapper/Sandbox/CloudServices/MapAccumulator/target/scala-2.11/strabo-assembly-0.0.1-SNAPSHOT.jar
conversion.kml.main_class: ai.mapper.app.AnnotatorToTiles
conversion.kml.input.path: ./data/annotations-lla.json
conversion.kml.output.path: ./data/annotator-tiles.kml
